- job-template:
    name: 'rest-autotests'
    description: 'Running REST autotests'
    project-type: pipeline
    concurrent: true
    logrotate:
      daysToKeep: 3
      numToKeep: 20
    parameters:
      - string:
          name: BRANCH
          default: main
          description: "Branch for tempest Rest OTUS tests"
    pipeline-scm:
      scm:
      - git-rest-autotests
      script-path: jenkins/rest-autotests.groovy